// Auto-generated Supabase types with tesoreria_cajas fix
export type Database = {
  public: {
    Tables: {
      usuarios: any;
      clientes: any;
      productos: any;
      lotes: any;
      movimientos_stock: any;
      checklists_calidad: any;
      pedidos: any;
      detalles_pedido: any;
      cotizaciones: any;
      detalles_cotizacion: any;
      reclamos: any;
      vehiculos: any;
      checklists_vehiculos: any;
      rutas_reparto: any;
      detalles_ruta: any;
      ubicaciones_repartidores: any;
      alertas_reparto: any;
      zonas: any;
      presupuestos: any;
      detalles_presupuesto: any;
      cuentas_corrientes: any;
      gastos: any;
      tesoreria_cajas: {
        Row: {
          id: string;
          sucursal_id: string | null;
          nombre: string;
          saldo_inicial: number;
          saldo_actual: number;
          moneda: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sucursal_id?: string | null;
          nombre: string;
          saldo_inicial?: number;
          saldo_actual?: number;
          moneda?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sucursal_id?: string | null;
          nombre?: string;
          saldo_inicial?: number;
          saldo_actual?: number;
          moneda?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tesoreria_movimientos: any;
      rutas_planificadas: any;
      // RRHH Tables
      sucursales: {
        Row: {
          id: string;
          nombre: string;
          direccion: string | null;
          telefono: string | null;
          encargado_id: string | null;
          activo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          direccion?: string | null;
          telefono?: string | null;
          encargado_id?: string | null;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          direccion?: string | null;
          telefono?: string | null;
          encargado_id?: string | null;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_categorias: {
        Row: {
          id: string;
          nombre: string;
          descripcion: string | null;
          sueldo_basico: number;
          adicional_cajero: number;
          adicional_produccion: number;
          activo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          descripcion?: string | null;
          sueldo_basico: number;
          adicional_cajero?: number;
          adicional_produccion?: number;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          descripcion?: string | null;
          sueldo_basico?: number;
          adicional_cajero?: number;
          adicional_produccion?: number;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_empleados: {
        Row: {
          id: string;
          usuario_id: string | null;
          sucursal_id: string | null;
          categoria_id: string | null;
          legajo: string | null;
          nombre: string | null;
          apellido: string | null;
          fecha_ingreso: string;
          fecha_nacimiento: string | null;
          dni: string | null;
          cuil: string | null;
          domicilio: string | null;
          telefono_personal: string | null;
          contacto_emergencia: string | null;
          telefono_emergencia: string | null;
          obra_social: string | null;
          numero_afiliado: string | null;
          banco: string | null;
          cbu: string | null;
          numero_cuenta: string | null;
          sueldo_actual: number | null;
          valor_jornal_presentismo: number | null;
          valor_hora: number | null;
          activo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          usuario_id?: string | null;
          sucursal_id?: string | null;
          categoria_id?: string | null;
          legajo?: string | null;
          nombre?: string | null;
          apellido?: string | null;
          fecha_ingreso: string;
          fecha_nacimiento?: string | null;
          dni?: string | null;
          cuil?: string | null;
          domicilio?: string | null;
          telefono_personal?: string | null;
          contacto_emergencia?: string | null;
          telefono_emergencia?: string | null;
          obra_social?: string | null;
          numero_afiliado?: string | null;
          banco?: string | null;
          cbu?: string | null;
          numero_cuenta?: string | null;
          sueldo_actual?: number | null;
          valor_jornal_presentismo?: number | null;
          valor_hora?: number | null;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          usuario_id?: string | null;
          sucursal_id?: string | null;
          categoria_id?: string | null;
          legajo?: string | null;
          nombre?: string | null;
          apellido?: string | null;
          fecha_ingreso?: string;
          fecha_nacimiento?: string | null;
          dni?: string | null;
          cuil?: string | null;
          domicilio?: string | null;
          telefono_personal?: string | null;
          contacto_emergencia?: string | null;
          telefono_emergencia?: string | null;
          obra_social?: string | null;
          numero_afiliado?: string | null;
          banco?: string | null;
          cbu?: string | null;
          numero_cuenta?: string | null;
          sueldo_actual?: number | null;
          valor_jornal_presentismo?: number | null;
          valor_hora?: number | null;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_novedades: {
        Row: {
          id: string;
          titulo: string;
          descripcion: string | null;
          tipo: string;
          sucursal_id: string | null;
          categoria_id: string | null;
          fecha_publicacion: string;
          fecha_expiracion: string | null;
          prioridad: string;
          activo: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          titulo: string;
          descripcion?: string | null;
          tipo: string;
          sucursal_id?: string | null;
          categoria_id?: string | null;
          fecha_publicacion?: string;
          fecha_expiracion?: string | null;
          prioridad?: string;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          titulo?: string;
          descripcion?: string | null;
          tipo?: string;
          sucursal_id?: string | null;
          categoria_id?: string | null;
          fecha_publicacion?: string;
          fecha_expiracion?: string | null;
          prioridad?: string;
          activo?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      rrhh_asistencia: {
        Row: {
          id: string;
          empleado_id: string;
          fecha: string;
          hora_entrada: string | null;
          hora_salida: string | null;
          horas_trabajadas: number | null;
          turno: string | null;
          estado: string;
          observaciones: string | null;
          retraso_minutos: number;
          falta_sin_aviso: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empleado_id: string;
          fecha: string;
          hora_entrada?: string | null;
          hora_salida?: string | null;
          horas_trabajadas?: number | null;
          turno?: string | null;
          estado?: string;
          observaciones?: string | null;
          retraso_minutos?: number;
          falta_sin_aviso?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empleado_id?: string;
          fecha?: string;
          hora_entrada?: string | null;
          hora_salida?: string | null;
          horas_trabajadas?: number | null;
          turno?: string | null;
          estado?: string;
          observaciones?: string | null;
          retraso_minutos?: number;
          falta_sin_aviso?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_licencias: {
        Row: {
          id: string;
          empleado_id: string;
          tipo: string;
          fecha_inicio: string;
          fecha_fin: string;
          dias_total: number;
          aprobado: boolean;
          aprobado_por: string | null;
          fecha_aprobacion: string | null;
          observaciones: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empleado_id: string;
          tipo: string;
          fecha_inicio: string;
          fecha_fin: string;
          dias_total: number;
          aprobado?: boolean;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empleado_id?: string;
          tipo?: string;
          fecha_inicio?: string;
          fecha_fin?: string;
          dias_total?: number;
          aprobado?: boolean;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_adelantos: {
        Row: {
          id: string;
          empleado_id: string;
          tipo: string;
          monto: number | null;
          producto_id: string | null;
          cantidad: number | null;
          precio_unitario: number | null;
          fecha_solicitud: string;
          aprobado: boolean;
          aprobado_por: string | null;
          fecha_aprobacion: string | null;
          porcentaje_sueldo: number | null;
          observaciones: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empleado_id: string;
          tipo: string;
          monto?: number | null;
          producto_id?: string | null;
          cantidad?: number | null;
          precio_unitario?: number | null;
          fecha_solicitud?: string;
          aprobado?: boolean;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          porcentaje_sueldo?: number | null;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empleado_id?: string;
          tipo?: string;
          monto?: number | null;
          producto_id?: string | null;
          cantidad?: number | null;
          precio_unitario?: number | null;
          fecha_solicitud?: string;
          aprobado?: boolean;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          porcentaje_sueldo?: number | null;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_liquidaciones: {
        Row: {
          id: string;
          empleado_id: string;
          periodo_mes: number;
          periodo_anio: number;
          fecha_liquidacion: string;
          sueldo_basico: number;
          adicional_cajero: number;
          adicional_produccion: number;
          horas_trabajadas: number;
          turnos_trabajados: number;
          horas_extras: number;
          valor_hora_extra: number;
          kg_producidos: number;
          valor_kg: number;
          total_bruto: number;
          descuentos_total: number;
          adelantos_total: number;
          total_neto: number;
          estado: string;
          aprobado_por: string | null;
          fecha_aprobacion: string | null;
          pagado: boolean;
          fecha_pago: string | null;
          observaciones: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empleado_id: string;
          periodo_mes: number;
          periodo_anio: number;
          fecha_liquidacion: string;
          sueldo_basico: number;
          adicional_cajero?: number;
          adicional_produccion?: number;
          horas_trabajadas?: number;
          turnos_trabajados?: number;
          horas_extras?: number;
          valor_hora_extra?: number;
          kg_producidos?: number;
          valor_kg?: number;
          total_bruto: number;
          descuentos_total?: number;
          adelantos_total?: number;
          total_neto: number;
          estado?: string;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          pagado?: boolean;
          fecha_pago?: string | null;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empleado_id?: string;
          periodo_mes?: number;
          periodo_anio?: number;
          fecha_liquidacion?: string;
          sueldo_basico?: number;
          adicional_cajero?: number;
          adicional_produccion?: number;
          horas_trabajadas?: number;
          turnos_trabajados?: number;
          horas_extras?: number;
          valor_hora_extra?: number;
          kg_producidos?: number;
          valor_kg?: number;
          total_bruto?: number;
          descuentos_total?: number;
          adelantos_total?: number;
          total_neto?: number;
          estado?: string;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          pagado?: boolean;
          fecha_pago?: string | null;
          observaciones?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      rrhh_liquidacion_detalles: {
        Row: {
          id: string;
          liquidacion_id: string;
          tipo: string;
          descripcion: string | null;
          monto: number;
          referencia_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          liquidacion_id: string;
          tipo: string;
          descripcion?: string | null;
          monto: number;
          referencia_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          liquidacion_id?: string;
          tipo?: string;
          descripcion?: string | null;
          monto?: number;
          referencia_id?: string | null;
          created_at?: string;
        };
      };
      rrhh_descuentos: {
        Row: {
          id: string;
          empleado_id: string;
          tipo: string;
          monto: number;
          fecha: string;
          motivo: string;
          observaciones: string | null;
          aprobado: boolean;
          aprobado_por: string | null;
          fecha_aprobacion: string | null;
          liquidacion_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empleado_id: string;
          tipo: string;
          fecha?: string;
          motivo: string;
          observaciones?: string | null;
          aprobado?: boolean;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          liquidacion_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empleado_id?: string;
          tipo?: string;
          monto?: number;
          fecha?: string;
          motivo?: string;
          observaciones?: string | null;
          aprobado?: boolean;
          aprobado_por?: string | null;
          fecha_aprobacion?: string | null;
          liquidacion_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rrhh_evaluaciones: {
        Row: {
          id: string;
          empleado_id: string;
          sucursal_id: string;
          periodo_mes: number;
          periodo_anio: number;
          puntualidad: number | null;
          rendimiento: number | null;
          actitud: number | null;
          responsabilidad: number | null;
          trabajo_equipo: number | null;
          promedio: number | null;
          fortalezas: string | null;
          areas_mejora: string | null;
          objetivos: string | null;
          comentarios: string | null;
          evaluador_id: string;
          fecha_evaluacion: string;
          estado: string;
          notificado: boolean;
          fecha_notificacion: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empleado_id: string;
          sucursal_id: string;
          periodo_mes: number;
          periodo_anio: number;
          puntualidad?: number | null;
          rendimiento?: number | null;
          actitud?: number | null;
          responsabilidad?: number | null;
          trabajo_equipo?: number | null;
          promedio?: number | null;
          fortalezas?: string | null;
          areas_mejora: string | null;
          objetivos?: string | null;
          comentarios?: string | null;
          evaluador_id: string;
          fecha_evaluacion?: string;
          estado?: string;
          notificado?: boolean;
          fecha_notificacion?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empleado_id?: string;
          sucursal_id?: string;
          periodo_mes?: number;
          periodo_anio?: number;
          puntualidad?: number | null;
          rendimiento?: number | null;
          actitud?: number | null;
          responsabilidad?: number | null;
          trabajo_equipo?: number | null;
          promedio?: number | null;
          fortalezas?: string | null;
          areas_mejora?: string | null;
          objetivos?: string | null;
          comentarios?: string | null;
          evaluador_id?: string;
          fecha_evaluacion?: string;
          estado?: string;
          notificado?: boolean;
          fecha_notificacion?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      [key: string]: any;
    };
    Views: {
      [key: string]: any;
    };
    Functions: {
      [key: string]: any;
    };
    Enums: {
      [key: string]: any;
    };
  };
};
