graph LR
    User(Usuario) --> web[Next.js App]
    web --> API[Server Actions]
    API --> DB[(Supabase PostgreSQL)]
    
    subgraph Ventas
        ClienteForm --> API
        PresupuestoForm --> API
    end
    
    subgraph Tesoreria
        Proveedores --> API
        Facturas --> API
        Pagos --> API
        Retiros --> API
        API --> Cajas[Movimientos Caja]
    end
    
    subgraph Lógica de Negocio
        API --> ListasPrecios[Listas de Precios]
        API --> Clientes[Gestión Clientes]
        ListasPrecios -.-> Clientes
    end
